site_name: Talks by automationhacks 
theme:
  name: material
  palette:
    primary: teal
  features:
    - navigation.tabs
google_analytics:
  - UA-177852015-1
  - auto
markdown_extensions:
  - meta
  - mdx_truly_sane_lists

